# Generated by Django 5.2.8 on 2026-07-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_portal_credentials(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Mapping = apps.get_model('identity', 'ApplicationUserMapping')
    Profile = apps.get_model('identity', 'PortalProfile')

    # Existing Marketing mappings already contain the stable Marketing local ID;
    # use that only to create the portal profile.  Do not migrate email or a hash.
    for mapping in Mapping.objects.filter(application='marketing_crm', is_active=True).iterator():
        Profile.objects.get_or_create(user_id=mapping.user_id, defaults={'marketing_user_id': mapping.external_user_id})
    Mapping.objects.filter(application='marketing_crm').delete()

    # Portal credentials from the former login flow must not remain usable or be
    # retained as identifier copies for ordinary users.
    for user in User.objects.filter(is_superuser=False).iterator():
        user.password = '!'
        user.email = ''
        user.username = f'portal-{user.pk}'
        user.save(update_fields=['password', 'email', 'username'])


def reverse_migrate_legacy_portal_credentials(apps, schema_editor):
    # Removed credentials and copied identifiers are intentionally irreversible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_seed_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAuthorizationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company')),
            ],
        ),
        migrations.CreateModel(
            name='PortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_user_id', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(migrate_legacy_portal_credentials, reverse_migrate_legacy_portal_credentials),
    ]
