# Generated by Django 5.2.8 on 2026-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_marketingauthorizationstate_portalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationusermapping',
            name='application',
            field=models.CharField(choices=[('salespie', 'SalesPie'), ('bdcrm', 'BDCRM')], max_length=32),
        ),
    ]
