"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
WORKSPACE_HOME = BASE_DIR.parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('PORTAL_SECRET_KEY', 'django-insecure-local-company-portal-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv(
        'PORTAL_ALLOWED_HOSTS',
        '127.0.0.1,localhost,192.168.1.56',
    ).split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'identity.apps.IdentityConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('PORTAL_DATABASE_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('PORTAL_DATABASE_NAME', 'portal_identity'),
        'USER': os.getenv('PORTAL_DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('PORTAL_DATABASE_PASSWORD', 'admin'),
        'HOST': os.getenv('PORTAL_DATABASE_HOST', '127.0.0.1'),
        'PORT': os.getenv('PORTAL_DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
}

PORTAL_SSO_SHARED_SECRET = os.getenv('PORTAL_SSO_SHARED_SECRET', 'change-this-local-shared-secret')
PORTAL_SSO_CODE_TTL_SECONDS = int(os.getenv('PORTAL_SSO_CODE_TTL_SECONDS', '60'))
MARKETING_CRM_URL = os.getenv('MARKETING_CRM_URL', 'http://192.168.1.56:5173')
# Marketing CRM authorization-code provider settings.  The client secret is used
# only for the portal-to-Marketing token exchange, never in a browser.
MARKETING_CRM_AUTHORIZE_URL = os.getenv('MARKETING_CRM_AUTHORIZE_URL', f'{MARKETING_CRM_URL}/api/sso/authorize/')
MARKETING_CRM_TOKEN_URL = os.getenv('MARKETING_CRM_TOKEN_URL', f'{MARKETING_CRM_URL}/api/sso/token/')
MARKETING_CRM_CLIENT_ID = os.getenv('MARKETING_CRM_CLIENT_ID', 'company-portal')
MARKETING_CRM_CLIENT_SECRET = os.getenv('MARKETING_CRM_CLIENT_SECRET', '')
MARKETING_CRM_REDIRECT_URI = os.getenv('MARKETING_CRM_REDIRECT_URI', 'http://localhost:8004/api/auth/marketing/callback/')
MARKETING_CRM_AUTH_STATE_TTL_SECONDS = int(os.getenv('MARKETING_CRM_AUTH_STATE_TTL_SECONDS', '300'))
MARKETING_CRM_TOKEN_TIMEOUT_SECONDS = int(os.getenv('MARKETING_CRM_TOKEN_TIMEOUT_SECONDS', '10'))
MARKETING_CRM_LOGIN_URL = os.getenv('MARKETING_CRM_LOGIN_URL', 'http://127.0.0.1:8003/api/login/')
BDCRM_ACCOUNT_LOOKUP_URL = os.getenv('BDCRM_ACCOUNT_LOOKUP_URL', 'http://127.0.0.1:8000/api/portal/company-account/')
SALESPIE_ACCOUNT_LOOKUP_URL = os.getenv('SALESPIE_ACCOUNT_LOOKUP_URL', 'http://127.0.0.1:8001/portal/company-account/')
SALESPIE_CRM_URL = os.getenv('SALESPIE_CRM_URL', 'http://192.168.1.56:8001')
BDCRM_URL = os.getenv('BDCRM_URL', 'http://192.168.1.56:8003')
PORTAL_FRONTEND_URL = os.getenv('PORTAL_FRONTEND_URL', 'http://192.168.1.56:8002')

PORTAL_AUTO_START_CRMS = env_bool('PORTAL_AUTO_START_CRMS', DEBUG)
PORTAL_AUTO_START_CRMS_ON_BOOT = env_bool('PORTAL_AUTO_START_CRMS_ON_BOOT', PORTAL_AUTO_START_CRMS)
PORTAL_AUTO_RESTART_UNHEALTHY_CRMS = env_bool('PORTAL_AUTO_RESTART_UNHEALTHY_CRMS', DEBUG)
PORTAL_AUTO_START_TIMEOUT_SECONDS = float(os.getenv('PORTAL_AUTO_START_TIMEOUT_SECONDS', '45'))
PORTAL_SERVICE_HEALTH_CACHE_SECONDS = float(os.getenv('PORTAL_SERVICE_HEALTH_CACHE_SECONDS', '5'))

NPM_COMMAND = os.getenv('PORTAL_NPM_COMMAND', 'npm.cmd' if os.name == 'nt' else 'npm')
CRM_LOCAL_SERVICES = {
    'marketing_crm': [
        {
            'name': 'Marketing CRM backend',
            'port': 8003,
            'health_url': 'http://127.0.0.1:8003/api/login/',
            'health_method': 'POST',
            'healthy_statuses': [400, 401, 403],
            'command': [sys.executable, 'manage.py', 'runserver', '127.0.0.1:8003', '--noreload'],
            'cwd': str(WORKSPACE_HOME / 'email_campaign_project-4' / 'backend'),
            'env': {'DJANGO_SETTINGS_MODULE': 'email_campaign_project.settings'},
        },
        {
            'name': 'Marketing CRM frontend',
            'component': 'frontend',
            'port': 5173,
            'health_url': 'http://127.0.0.1:5173/',
            'accept': 'text/html',
            'healthy_statuses': [200],
            'command': [NPM_COMMAND, 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '5173'],
            'cwd': str(WORKSPACE_HOME / 'email_campaign_project-4' / 'frontend'),
        },
    ],
    'salespie': [
        {
            'name': 'SalesPie backend',
            'port': 8001,
            'health_url': 'http://127.0.0.1:8001/api/company-portal-login/',
            'health_method': 'POST',
            'healthy_statuses': [400, 401, 403],
            'command': [sys.executable, 'manage.py', 'runserver', '127.0.0.1:8001', '--noreload'],
            'cwd': str(WORKSPACE_HOME / 'SalesPie' / 'backend'),
            'env': {'DJANGO_SETTINGS_MODULE': 'spplus.settings'},
        },
        {
            'name': 'SalesPie frontend',
            'component': 'frontend',
            'port': 5174,
            'health_url': 'http://127.0.0.1:5174/',
            'accept': 'text/html',
            'healthy_statuses': [200],
            'command': [NPM_COMMAND, 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '5174'],
            'cwd': str(WORKSPACE_HOME / 'SalesPie' / 'frontend'),
        },
    ],
    'bdcrm': [
        {
            'name': 'BDCRM backend',
            'port': 8000,
            'health_url': 'http://127.0.0.1:8000/api/auth/company-portal-login/',
            'health_method': 'POST',
            'healthy_statuses': [400, 401, 403],
            'command': [sys.executable, 'manage.py', 'runserver', '127.0.0.1:8000', '--noreload'],
            'cwd': str(WORKSPACE_HOME / 'BDCRM-1' / 'BDCRM' / 'bdcrm'),
            # BDCRM routes Contact queries through its contacts_db alias. Keep
            # it on the existing BDCRM database when the portal supervises it.
            'env': {
                'DJANGO_SETTINGS_MODULE': 'bdcrm.settings',
                'CONTACTS_DATABASE_NAME': 'BDCRM',
            },
        },
        {
            'name': 'BDCRM frontend',
            'component': 'frontend',
            'port': 5175,
            'health_url': 'http://127.0.0.1:5175/',
            'accept': 'text/html',
            'healthy_statuses': [200],
            'command': [NPM_COMMAND, 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '5175'],
            'cwd': str(WORKSPACE_HOME / 'BDCRM-1' / 'frontend'),
        },
    ],
}
